# Temporal Workflow Engine Docker Compose

services:
  postgresql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    networks:
      - temporal-network
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data

  temporal:
    image: temporalio/auto-setup:1.27.2
    depends_on:
      - postgresql
    environment:
      # Service configuration
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/config.yaml  # Dynamic config path - Location of dynamic configuration file
      - TEMPORAL_ADDRESS=temporal:7233    # Temporal service address - Internal address for Temporal services communication
      - TEMPORAL_CLI_ADDRESS=temporal:7233  # CLI address - Address for Temporal CLI tools to connect to the server
      - PROMETHEUS_ENDPOINT=0.0.0.0:8000  # Prometheus endpoint - Address to expose metrics for monitoring systems

      # Database configuration
      - DB=postgres12                     # Database type (postgres12, mysql8, etc.) - Specifies which database driver to use
      - DB_PORT=5432                      # Database port - The port on which the database server is listening
      - POSTGRES_USER=temporal            # Database username - User with permissions to create and modify databases
      - POSTGRES_PWD=temporal             # Database password - Password for the database user
      - POSTGRES_SEEDS=postgresql         # Database host(s) - Comma-separated list of database servers (service names in docker-compose)
      - DBNAME=temporal                   # Main database name - Stores workflow execution history and task queues
      - VISIBILITY_DBNAME=temporal_visibility  # Visibility database name - Stores metadata for workflow search and visibility

      - LOG_LEVEL=debug,info

      # Schema setup configuration
      - SKIP_SCHEMA_SETUP=false           # Skip schema setup - Set to true to skip automatic schema initialization
      - SKIP_DB_CREATE=false              # Skip database creation - Set to true if databases already exist

      # Namespace configuration
      - DEFAULT_NAMESPACE=default         # Default namespace - Name of the default namespace to create
      - DEFAULT_NAMESPACE_RETENTION=7d     # Retention period = default 24h (using Go Duration standard)
      - SKIP_DEFAULT_NAMESPACE_CREATION=false  # Skip namespace creation - Set to true to skip creating default namespace
      - SKIP_ADD_CUSTOM_SEARCH_ATTRIBUTES=false  # Skip custom search attributes - Set to true to skip adding custom search attributes
    networks:
      - temporal-network
    ports:
      - "7233:7233"
      - "8000:8000"
    volumes:
      - ./temporal:/etc/temporal/config/dynamicconfig

  temporal-admin-tools:
    image: temporalio/admin-tools:1.27.2-tctl-1.18.2-cli-1.3.0
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    networks:
      - temporal-network
    stdin_open: true
    tty: true

  temporal-ui:
    image: temporalio/ui:2.34.0
    container_name: temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    networks:
      - temporal-network
    ports:
      - "8080:8080"

networks:
  temporal-network:
